### ISSUE TITLE
Возможность авторизоваться заново

### ISSUE THREAD

**Issue by mcmimik** [jastkand/vk-notifications#13]
Если выйти со всех сессий в настройках безопасности ВК, то доступ у расширения теряется, из-за чего приходится удалять его, устанавливать заново, добавлять все группы ещё раз... Добавьте, пожалуйста, возможность авторизоваться заново в настройках.

**Comment by jastkand** [comment]
@mcmimik Большое спасибо, постараюсь исправить в ближайшее время
