### ISSUE TITLE
Быстрый переход на новость

### ISSUE THREAD

**Issue by AlexKorovyansky** [jastkand/vk-notifications#6]
Хотелось бы иметь возможность быстрого перехода на новость, путем клика по ее времени (как в твиттере и во всех соц сетях)

![screen_shot_2014-02-26_at_10_12_03-7](https://f.cloud.github.com/assets/479961/2266271/37ca3b8c-9e94-11e3-871b-7bd71795cff8.png)

Я думаю, это очень просто сделать. Может быть я даже сам могу это сделать и выслать pull request.

@jastkand что думаешь?

**Comment by and7ey** [comment]
Поддерживаю - возможности быстрого перехода к новости очень не хватает.
